# Generated by Django 4.1.6 on 2023-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='student')),
                ('studentid', models.IntegerField(verbose_name='student id')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('password', models.TextField(verbose_name='password')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
