# Generated by Django 4.1.6 on 2023-02-10 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 3 characters')], verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')], verbose_name='password'),
        ),
    ]
