# Generated by Django 4.0.6 on 2023-02-10 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_name_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 3 characters')], verbose_name='student')),
                ('studentid', models.IntegerField(verbose_name='student id')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')], verbose_name='password')),
                ('images', models.ImageField(upload_to='images/studets', verbose_name='products images')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
